FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB redhatpedal
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD your_password  # Replace with your password

# Copy the initialization script
COPY ./init.sql /docker-entrypoint-initdb.d/
